# Mineshaft RPG configuration file.

# Worlds in which some features are disabled
# Currently this only includes updating the experience bar
disabled-worlds:
  - world1
  - world2

default-language: Westron

# BetonQuest event which should be triggered when the player is given their starting items
default-item-bq-event-package: default
default-item-bq-event: give_items

# Whether a hardcoded beton quest event is run
# Name: give_items_<culture>
# Only for hadcoded cultures
# e.g. give_items_hobbits_shire
run-hardcoded-bq-event: true

# The number of Skill Points the player starts the game with.
default-skill-points: 15

# The default attribute value.
default-ability-score-value: 8

# Experience required to reach each level,
# This list displays total xp, not from last level.
# This list can be extended to allow for more levels
experience-per-level:
  - 0        #Lv1
  - 300
  - 900
  - 2700
  - 6500     #Lv5
  - 14000
  - 23000
  - 34000
  - 48000
  - 64000    #Lv10
  - 85000
  - 100000
  - 120000
  - 140000
  - 165000   #Lv15
  - 195000
  - 225000
  - 265000
  - 305000
  - 355000   #Lv20

maximum-ability-score-per-level:
  1: 15
  2: 16
  3: 16
  4: 16
  5: 18
  10: 20
  15: 20
  20: 20


# Placeholder:
# culture-params:
#  hobbits_shire: []
#  dwarf_lonely_mountain: []
#  elf_mirkwood: []
#  human_bardings: []
#  human_beornings: []
#  human_dunedain: []
#  human_bree: []
#  human_laketown: []
#  human_minas_tirith: []
#  human_rohan: []
#  human_wilderland: []
